forms:
  finance-pst:
    path: /liquor/license
    type: issue-credential
    schema_name: Liquor License
    page_title: Liquor Control and Licensing Branch
    title: Liquor Control and Licensing Branch
    template: bcgov.index.html
    description: >
      Liquor License
    explanation: Use the form below to obtain a liquor license.

    proof_request:
      id: registration
      connection_id: bctob

    fields:
      - name: corp_num
        label: Corporation ID
        type: text
        required: true
        # disabled: true

      # - name: dba_corp_num
      #   label: Doing Business As ID
      #   type: text
      #   required: true
      #   disabled: true

      - name: legal_name
        label: Legal Name
        type: text
        required: true
        # disabled: true

      # - name: doing_business_as_name
      #   label: Doing Business As Name
      #   type: text
      #   required: true
      #   disabled: true

      - name: dancing_permitted
        label: >
          Patron Participation Entertainment - dancing, karaoke or other types entertainment
          that involve patron participation in the service area
        type: radio
        options:
          - value: true
            label: Yes
          - value: false
            label: No
        required: true

      - name: patio
        label: Are you applying for a patio?
        type: radio
        options:
          - value: true
            label: Yes
          - value: false
            label: No
        required: true

      - name: effective_date
        label: Effective Date
        type: date
        required: true
