issuers:
  bcreg:
    logo_path: ''
    name: BC Corporate Registry
    abbreviation: BCReg
    email: bcreg.test.issuer@example.ca
    url: https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/citizens-services/bc-registries-online-services
    endpoint: ${ENDPOINT_URL}/bcreg

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    wallet:
      name: ${POSTGRESQL_WALLET_NAME:-bcreg_issuer}
      seed: $INDY_WALLET_SEED
      type: $INDY_WALLET_TYPE
      params:
        storage_config:
          url: "$POSTGRESQL_WALLET_HOST:$POSTGRESQL_WALLET_PORT"
      access_creds:
        key: $WALLET_ENCRYPTION_KEY
        storage_credentials:
          account: $POSTGRESQL_WALLET_USER
          password: $POSTGRESQL_WALLET_PASSWORD
          admin_account: ${POSTGRESQL_WALLET_ADMIN_USER:-postgres}
          admin_password: $POSTGRESQL_WALLET_ADMIN_PASSWORD
        key_derivation_method: ARGON2I_MOD

    credential_types:
      - description: Registration
        schema: Registered Corporation
        issuer_url: $APPLICATION_URL/bcreg/incorporation
        topic:
          source_id:
            input: corp_num
            from: claim
          type:
            input: registration
            from: value
        mapping:
          - model: name
            fields:
              text:
                input: legal_name
                from: claim
              type:
                input: legal_name
                from: value
          - model: address
            fields:
              addressee:
                input: addressee
                from: claim
              civic_address:
                input: address_line_1
                from: claim
              city:
                input: city
                from: claim
              province:
                input: province
                from: claim
              postal_code:
                input: postal_code
                from: claim
              country:
                input: country
                from: claim
          - model: attribute
            fields:
              type:
                input: registration_date
                from: value
              format:
                input: datetime
                from: value
              value:
                input: registration_date
                from: claim
          - model: attribute
            fields:
              type:
                input: entity_type
                from: value
              format:
                input: category
                from: value
              value:
                input: entity_type
                from: claim
          - model: attribute
            fields:
              type:
                input: entity_status
                from: value
              format:
                input: category
                from: value
              value:
                input: entity_status
                from: claim
          - model: attribute
            fields:
              type:
                input: entity_status_effective
                from: value
              format:
                input: datetime
                from: value
              value:
                input: entity_status_effective
                from: claim
          - model: attribute
            fields:
              type:
                input: entity_name_effective
                from: value
              format:
                input: datetime
                from: value
              value:
                input: entity_name_effective
                from: claim


      - description: Relationship
        schema: Business Relationship
        issuer_url: $APPLICATION_URL/bcreg/dba
        credential:
          effective_date:
            input: effective_date
            from: claim
        topic:
          related_source_id:
            input: dba_corp_num
            from: claim
          related_type:
            input: registration
            from: value
          source_id:
            input: corp_num
            from: claim
          type:
            input: registration
            from: value
        cardinality_fields:
          - dba_corp_num
        mapping:
          - model: category
            fields:
              type:
                input: relationship
                from: value
              value:
                input: relationship
                from: claim
          - model: attribute
            fields:
              type:
                input: relationship_description
                from: value
              value:
                input: relationship_description
                from: claim
          - model: category
            fields:
              type:
                input: relationship_status
                from: value
              value:
                input: relationship_status
                from: claim
          - model: attribute
            fields:
              type:
                input: relationship_status_effective
                from: value
              format:
                input: datetime
                from: value
              value:
                input: relationship_status_effective
                from: claim
          - model: attribute
            fields:
              type:
                input: reason_description
                from: value
              value:
                input: reason_description
                from: claim

# verifiers:
#   bctob:
#     name: BC OrgBook
#     connection:
#       type: TheOrgBook
#       api_url: $TOB_API_URL
#     wallet:
#       seed: "tob-verifier-wallet-000000000001"


# proof_requests:
#   registration:
#     version: '1.0.3'
#     schemas:
#       - key:
#           name: Registered Corporation
#           version: '1.0.3'
#         attributes:
#           - corp_num
#           - address_line_1
#           - address_line_2
#           - addressee
#           - city
#           - country
#           - legal_name
#           - postal_code
#           - province

