issuers:
  surrey:
    logo_path: ''
    name: City of Surrey
    abbreviation: SUR
    email: surrey.test.issuer@example.ca
    url: https://www.surrey.ca/
    endpoint: ${ENDPOINT_URL}/surrey

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    wallet:
      name: ${POSTGRESQL_WALLET_NAME:-surrey_issuer}
      seed: $INDY_WALLET_SEED
      type: $INDY_WALLET_TYPE
      params:
        storage_config:
          url: "$POSTGRESQL_WALLET_HOST:$POSTGRESQL_WALLET_PORT"
      access_creds:
        key: $WALLET_ENCRYPTION_KEY
        storage_credentials:
          account: $POSTGRESQL_WALLET_USER
          password: $POSTGRESQL_WALLET_PASSWORD
          admin_account: ${POSTGRESQL_WALLET_ADMIN_USER:-postgres}
          admin_password: $POSTGRESQL_WALLET_ADMIN_PASSWORD
        key_derivation_method: ARGON2I_MOD

    credential_types:
      - description: Business License
        schema: Business License
        issuer_url: $APPLICATION_URL/surrey/biz
        depends_on:
          - liquor-license
        topic:
          source_id:
            input: corp_num
            from: claim
          type:
            input: registration
            from: value


verifiers:
  bctob:
    name: BC OrgBook
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
    wallet:
      seed: "tob-verifier-wallet-000000000001"

proof_requests:
  registration:
    version: '1.0.3'
    schemas:
      - key:
          did: 6qnvgJtqwK44D8LFYnV5Yf
          name: Registered Corporation
          version: '1.0.3'
        attributes:
          - corp_num
          - legal_name
  pst-number:
    version: '1.0.3'
    schemas:
      - key:
          did: CYnWiuEtJJuhpWvVz3kY9D
          name: PST Number
          version: '1.0.3'
        attributes:
          - corp_num
  clearance-letter:
    version: '1.0.3'
    schemas:
      - key:
          did: MAcounf9HxhgnqqhzReTLC
          name: WorkSafe BC Coverage
          version: '1.0.3'
        attributes:
          - corp_num
  operating-permit:
    version: '1.0.3'
    schemas:
      - key:
          did: L6SJy7gNRCLUp8dV94hfex
          name: Operating Permit
          version: '1.0.3'
        attributes:
          - corp_num
  liquor-license:
    version: '1.0.3'
    schemas:
      - key:
          did: ScrMddP9C426QPrp1KViZB
          name: Liquor License
          version: '1.0.3'
        attributes:
          - corp_num
