issuers:
  fraser-valley:
    logo_path: ''
    name: Fraser Valley Health Authority
    abbreviation: FRV
    email: frv.test.issuer@example.ca
    url: https://www.fraserhealth.ca/
    endpoint: ${ENDPOINT_URL}/fraser-valley

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    wallet:
      name: ${POSTGRESQL_WALLET_NAME:-fraser_issuer}
      seed: $INDY_WALLET_SEED
      type: $INDY_WALLET_TYPE
      params:
        storage_config:
          url: "$POSTGRESQL_WALLET_HOST:$POSTGRESQL_WALLET_PORT"
      access_creds:
        key: $WALLET_ENCRYPTION_KEY
        storage_credentials:
          account: $POSTGRESQL_WALLET_USER
          password: $POSTGRESQL_WALLET_PASSWORD
          admin_account: ${POSTGRESQL_WALLET_ADMIN_USER:-postgres}
          admin_password: $POSTGRESQL_WALLET_ADMIN_PASSWORD
        key_derivation_method: ARGON2I_MOD

    credential_types:
      - description: Operating Permit
        schema: Operating Permit
        issuer_url: $APPLICATION_URL/fraser-valley/permit
        depends_on:
          - clearance-letter
        topic:
          source_id:
            input: corp_num
            from: claim
          type:
            input: registration
            from: value
verifiers:
  bctob:
    name: BC OrgBook
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
    wallet:
      seed: "tob-verifier-wallet-000000000001"

proof_requests:
  registration:
    version: '1.0.3'
    schemas:
      - key:
          did: 6qnvgJtqwK44D8LFYnV5Yf
          name: Registered Corporation
          version: '1.0.3'
        attributes:
          - corp_num
          - legal_name
  clearance-letter:
    version: '1.0.3'
    schemas:
      - key:
          did: MAcounf9HxhgnqqhzReTLC
          name: WorkSafe BC Coverage
          version: '1.0.3'
        attributes:
          - corp_num
