forms:
  finance-pst:
    path: /finance/pst
    type: issue-credential
    schema_name: PST Number
    page_title: Ministry of Finance
    title: PST Number
    template: bcgov.index.html
    description: >
      Obtain a PST number
    explanation: Use the form below to obtain a PST number.

    proof_request:
      id: registration
      connection_id: bctob

    fields:
      - name: corp_num
        label: Corporation ID
        type: text
        required: true

      # - name: dba_corp_num
      #   label: Doing Business As ID
      #   type: text
      #   required: true
      #   disabled: true

      - name: legal_name
        label: Legal Name
        type: text
        required: true

      # - name: doing_business_as_name
      #   label: Doing Business As Name
      #   type: text
      #   required: true
      #   disabled: true

    mapping:
      attributes:
        - name: pst_number
          from: helper
          source: pst